import { MigrateOptions } from "fireblaze";

// Can't create new collection here, it's generated by itself when adding a new doc

export async function migrate({ firestore }: MigrateOptions) {
  // Get a new write batch
  const batch = firestore.batch();

  const transactions = await firestore.collection("transaction").get();
  await Promise.all(
    transactions.docs.map(async (snapshot) => {
      const doc = snapshot.ref;
      //await doc.update({ group: null });
      batch.update(doc, { group: null });
    }),
  );
  // Commit the batch
  await batch.commit();
}
